#!/usr/bin/env python3
"""Lock and verify the structured inputs used by the 3080 HTML composer."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


GENERATOR = "3080-brief-html-composer"
CONTRACT_VERSION = "1.0"
GENERATOR_COMMENT = "<!-- Generated by 3080 Brief HTML Composer -->"


def digest_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def digest_file(path: Path) -> str:
    return digest_bytes(path.read_bytes())


def canonical_digest(value: object) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return digest_bytes(payload)


def load_json(path: Path, label: str) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{label} unavailable: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{label} must contain a JSON object")
    return value


def input_record(path: Path) -> dict:
    return {
        "path": str(path.resolve()),
        "sha256": digest_file(path),
        "bytes": path.stat().st_size,
    }


def create_contract(brief_path: Path, visual_spec_path: Path, design_plan_path: Path, output_path: Path) -> dict:
    brief = load_json(brief_path, "brief")
    visual_spec = load_json(visual_spec_path, "visual spec")
    design_plan = load_json(design_plan_path, "HTML design plan")
    contract = {
        "schema_version": 1,
        "contract_version": CONTRACT_VERSION,
        "status": "locked",
        "generator": GENERATOR,
        "inputs": {
            "brief": input_record(brief_path),
            "visual_spec": input_record(visual_spec_path),
            "html_design": input_record(design_plan_path),
        },
        "decisions": {
            "language": brief.get("language"),
            "theme": visual_spec.get("style"),
            "composition": visual_spec.get("composition"),
            "layout": design_plan.get("layout"),
            "density": design_plan.get("density"),
            "figure_treatment": (design_plan.get("body") or {}).get("figure_treatment"),
            "section_treatment": (design_plan.get("body") or {}).get("section_treatment"),
            "one_picture_renderer": (design_plan.get("one_picture") or {}).get("renderer"),
        },
        "output": {
            "path": str(output_path.resolve()),
            "format": "html",
        },
    }
    contract["contract_id"] = canonical_digest(contract)
    return contract


def validate_contract(
    contract: dict,
    brief_path: Path,
    visual_spec_path: Path,
    design_plan_path: Path,
    output_path: Path,
) -> list[str]:
    errors: list[str] = []
    if contract.get("schema_version") != 1 or contract.get("contract_version") != CONTRACT_VERSION:
        errors.append("HTML runtime contract version is unsupported")
    if contract.get("status") != "locked" or contract.get("generator") != GENERATOR:
        errors.append("HTML runtime contract is not locked to the 3080 composer")
    expected_id = contract.get("contract_id")
    unlocked = dict(contract)
    unlocked.pop("contract_id", None)
    if expected_id != canonical_digest(unlocked):
        errors.append("HTML runtime contract lock hash is invalid")
    expected_inputs = {
        "brief": brief_path,
        "visual_spec": visual_spec_path,
        "html_design": design_plan_path,
    }
    for key, path in expected_inputs.items():
        record = (contract.get("inputs") or {}).get(key) or {}
        if record.get("sha256") != digest_file(path):
            errors.append(f"HTML runtime contract {key} hash differs from the current file")
    if str((contract.get("output") or {}).get("path", "")) != str(output_path.resolve()):
        errors.append("HTML runtime contract output path differs from the requested artifact")
    return errors


def write_contract(path: Path, contract: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(contract, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_receipt(path: Path, contract: dict, output_path: Path, warnings: list[str]) -> dict:
    receipt = {
        "schema_version": 1,
        "status": "built",
        "generator": GENERATOR,
        "contract_id": contract["contract_id"],
        "artifact": {
            "path": str(output_path.resolve()),
            "sha256": digest_file(output_path),
            "bytes": output_path.stat().st_size,
        },
        "inputs": {
            key: value["sha256"] for key, value in contract["inputs"].items()
        },
        "warnings": list(warnings),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(receipt, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return receipt


def verify_receipt(receipt: dict, contract: dict, output_path: Path) -> list[str]:
    errors: list[str] = []
    if receipt.get("schema_version") != 1 or receipt.get("status") != "built":
        errors.append("HTML build receipt is not complete")
    if receipt.get("generator") != GENERATOR or receipt.get("contract_id") != contract.get("contract_id"):
        errors.append("HTML build receipt is not bound to the locked contract")
    artifact = receipt.get("artifact") or {}
    if artifact.get("sha256") != digest_file(output_path):
        errors.append("HTML build receipt artifact hash differs from the delivered file")
    expected_inputs = {key: value["sha256"] for key, value in (contract.get("inputs") or {}).items()}
    if receipt.get("inputs") != expected_inputs:
        errors.append("HTML build receipt input hashes differ from the locked contract")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser("init")
    init.add_argument("--brief", required=True, type=Path)
    init.add_argument("--visual-spec", required=True, type=Path)
    init.add_argument("--design-plan", required=True, type=Path)
    init.add_argument("--output-html", required=True, type=Path)
    init.add_argument("--contract", required=True, type=Path)

    verify = subparsers.add_parser("verify")
    verify.add_argument("--brief", required=True, type=Path)
    verify.add_argument("--visual-spec", required=True, type=Path)
    verify.add_argument("--design-plan", required=True, type=Path)
    verify.add_argument("--output-html", required=True, type=Path)
    verify.add_argument("--contract", required=True, type=Path)
    verify.add_argument("--receipt", required=True, type=Path)

    args = parser.parse_args()
    try:
        if args.command == "init":
            contract = create_contract(args.brief, args.visual_spec, args.design_plan, args.output_html)
            write_contract(args.contract, contract)
            print(f"LOCKED {contract['contract_id']} | {args.contract}")
            return 0

        contract = load_json(args.contract, "HTML runtime contract")
        receipt = load_json(args.receipt, "HTML build receipt")
        errors = validate_contract(contract, args.brief, args.visual_spec, args.design_plan, args.output_html)
        if args.output_html.is_file():
            errors.extend(verify_receipt(receipt, contract, args.output_html))
        else:
            errors.append(f"HTML artifact is missing: {args.output_html}")
    except ValueError as exc:
        errors = [str(exc)]
    if errors:
        print("FAIL")
        for error in errors:
            print(f"ERROR {error}")
        return 1
    print(f"PASS {contract['contract_id']} | {args.output_html}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
